steps:
  - read: component
    prompt: What is the name of your component? (Uppercase)

  - read: package_name
    prompt: What is the name of the package?
    default:
      from: filesystem.rootdir

  - read: remote_url
    from: git.remote_url
    fallback: '{{ git remote url }}'

  - read: owner_name
    from: git.author_name
    fallback:
      prompt: What is your name?

  - read: owner_email
    from: git.author_email
    fallback:
      prompt: What is your email address?

  - update: preview/App.tsx
  - update: src/index.ts
  - update: src/component/index.tsx
  - update: src/test/some.test.tsx
  - update: CODE_OF_CONDUCT.md
  - update: LICENSE
  - update: package.json
  - remove: README.md
  - copy: README.tmpl.md
    to: README.md
  - remove: README.tmpl.md
  - remove: .tmplr.yml
