name: Publish to NPM
on:
  push:
    branches:
      - main
      - master
jobs:
  check-env:
    runs-on: ubuntu-latest
    outputs:
      check: ${{ steps.check.outputs.check }}
    steps:
      - id: check
        env:
          NPM_AUTH_TOKEN: '${{ secrets.NPM_AUTH_TOKEN }}'
        if: "${{ env.NPM_AUTH_TOKEN != ''}}"
        run: echo "::set-output name=check::true"
  do:
    needs: [check-env]
    if: needs.check-env.outputs.check == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
      
      - name: Build
        run: npm run build

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
