name: Report Coverage to Codecov
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
jobs:
  do:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm ci

      - name: Generate Coverage Report
        run: npm run coverage

      - name: Upload to Codecov
        uses: codecov/codecov-action@v1

